// Darius Star: Cyber Coelacanth — ES Module Entry Point
// Generated by es_module_converter.py (Fred, GRO-1064)
// Load order preserved from original index.html dependency chain
//
// Each module uses side-effect imports to maintain global scope
// compatibility while enabling proper ES module graph in DevTools.
// Full explicit import conversion is Phase 2.

import './js/utils.js';
import './js/canvas_setup.js';
import './js/upgrade_system.js';
import './js/save_system.js';
import './js/player_state.js';
import './js/combo.js';
import './js/economy.js';
import './js/scrap_events.js';
import './js/banter_db.js';
import './js/banter_engine.js';
import './js/multiplayer.js';
import './js/ngplus.js';
import './js/leaderboard.js';
import './js/player.js';
import './js/enemies.js';
import './js/combat.js';
import './js/renderer/parallax.js';
import './js/renderer/particles.js';
import './js/renderer.js';
import './js/sprites.js';
import './js/audio.js';
import './js/ui/menus.js';
import './js/ui/hud.js';
import './js/ui/ship-select.js';
import './js/ui/settings.js';
import './js/ui/game-over.js';
import './js/ui.js';
import './js/audio_chip.js';
import './js/audio_manager.js';
import './js/voice_playback.js';
import './js/ui/dialogue.js';
import './js/ui/briefing.js';
import './js/levels/biome_data.js';
import './js/levels/wave_campaign.js';
import './js/level_manager.js';
import './js/game_loop.js';
import './js/story/branching.js';
import './js/story/audio-tunnels.js';
import './js/story/triggers.js';
import './js/touch_controls.js';
import './js/i18n/de.js';
import './js/i18n/en.js';
import './js/i18n/es.js';
import './js/i18n/ja.js';
import './js/i18n.js';
import './js/main.js';

console.log("[Darius Star] ES Module graph loaded. 46 modules.");
