// js/levels/biome_data.js — Biome and 100-Level Journey Metadata (GRO-1063 & GRO-1140)
// Complete 10-Biome x 10-Level campaign structure with unique landmarks, lighting palettes, and intel logs.

const BIOME_DATA = {
  enemies: {
    1: { scout:'angler_scout', interceptor:'jelly_interceptor', heavy:'vent_crab_heavy', alt:'trench_eel' },
    2: { scout:'rust_drone', interceptor:'coral_wasp', heavy:'armored_eel', alt:'spine_urchin' },
    3: { scout:'sparker', interceptor:'sentinel', heavy:'juggernaut', alt:'boss_minion' },
    4: { scout:'plasma_wisp', interceptor:'storm_sprite', heavy:'gas_giant', alt:'nebula_wraith' },
    5: { scout:'ice_shard', interceptor:'frost_drone', heavy:'glacier', alt:'ice_swarm' },
    6: { scout:'ember_sprite', interceptor:'magma_wasp', heavy:'lava_golem', alt:'inferno_node' },
    7: { scout:'static_spark', interceptor:'storm_hawk', heavy:'thunderhead', alt:'storm_sentinel' },
    8: { scout:'salvage_drone', interceptor:'ghost_fighter', heavy:'turret_battery', alt:'fleet_turret' },
    9: { scout:'crawler', interceptor:'spitter', heavy:'brute', alt:'hive_node' },
    10:{ scout:'glitch_fragment', interceptor:'paradox_wisp', heavy:'null_entity', alt:'rift_aberration' }
  },
  names: {
    1:'Abyssal Trench', 2:'Coral Graveyard', 3:'Coelacanth\'s Lair',
    4:'Nebula Drift', 5:'Ice Ring', 6:'Fire Nebula',
    7:'Storm Belt', 8:'Derelict Fleet', 9:'Xenomorph Hive',
    10:'Core Rift'
  },
  bossHP: {
    1:{ midBoss:60, biomeBoss:120 }, 2:{ midBoss:80, biomeBoss:150 },
    3:{ midBoss:100, biomeBoss:200 }, 4:{ midBoss:120, biomeBoss:180 },
    5:{ midBoss:140, biomeBoss:200 }, 6:{ midBoss:160, biomeBoss:220 },
    7:{ midBoss:180, biomeBoss:240 }, 8:{ midBoss:200, biomeBoss:260 },
    9:{ midBoss:220, biomeBoss:280 }, 10:{ midBoss:240, biomeBoss:400 }
  },
  // ─── 100-LEVEL JOURNEY METADATA ──────────────────────────────────────────
  levelDetails: {
    1: {
      1: {
        name: "1.1 Sector",
        shortName: "1.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Crushing Hydrostatic Pressure",
        classifiedLog: "Marcus Star Log #01: We breached the Mariana crust at 11,000 meters. The sonar echoes aren't bouncing off rock—something is absorbing sound.",
        commLine: { s: "D", l: "Sunlight's fading fast. The trench mouth opens ahead." }
      },
      2: {
        name: "1.2 Sector",
        shortName: "1.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Bioluminescent Drone Swarms",
        classifiedLog: "Haven-7 Survey: Coral polyp clusters here generate coherent laser frequencies when stimulated by intruders.",
        commLine: { s: "L", l: "Daddy, the reef is lighting up... it's calling for defenders." }
      },
      3: {
        name: "1.3 Sector",
        shortName: "1.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Hull Structural Decompression",
        classifiedLog: "Scrap Recovery Memo: This exploration frigate went dark in 2048. Its hull plating is fused with living coelacanth scales.",
        commLine: { s: "N", l: "Old Terran wreckage detected. Useful alloys for the quantum fabricator." }
      },
      4: {
        name: "1.4 Sector",
        shortName: "1.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Vertical Gravity Sinks",
        classifiedLog: "Marcus Star Log #04: The chasm pulled our bathysphere downward at 30 knots. Natural currents don't move like this.",
        commLine: { s: "D", l: "Hold on to your thrusters. The bottom just dropped out." }
      },
      5: {
        name: "1.5 Sector",
        shortName: "1.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Precursor Quantum Pings",
        classifiedLog: "Navy Surveillance Intercept: Precursor beacon transmitting 4.8 THz quantum carrier wave toward Jupiter.",
        commLine: { s: "T", l: "That sensor buoy is pinging our location. Blast it before it calls the fleet." }
      },
      6: {
        name: "1.6 Sector",
        shortName: "1.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Submerged Aqueduct Cross-Currents",
        classifiedLog: "Haven-7 Xenology: Aqueducts carved from monomolecular carbon. They carried biosynthetic amniotic fluids.",
        commLine: { s: "N", l: "These ancient stone channels were built to nurture prototypes." }
      },
      7: {
        name: "1.7 Sector",
        shortName: "1.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Neurotoxic Bio-Spores",
        classifiedLog: "Medical Log: Kelp fronds release microscopic spores that induce hallucinations and temporal disorientation.",
        commLine: { s: "L", l: "The green light is dancing across the cockpit. I can hear distant humming." }
      },
      8: {
        name: "1.8 Sector",
        shortName: "1.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Superheated Sulfur Plumes",
        classifiedLog: "Thermal Analysis: Vent chimneys discharging 450°C mineral slurry. Thermal shield integrity mandatory.",
        commLine: { s: "D", l: "Thermal chimneys blowing black smoke! Watch your temperature gauges." }
      },
      9: {
        name: "1.9 Sector",
        shortName: "1.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Automated Sea-Gate Artillery",
        classifiedLog: "Tactical Recon: Titanium fortress gates armed with magnetic rail cannons. Break through the perimeter.",
        commLine: { s: "N", l: "Fortress gate perimeter sighted. Heavy defensive resistance inbound." }
      },
      10: {
        name: "1.10 Sector",
        shortName: "1.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Apex Biome Leviathan Resonance",
        classifiedLog: "Classified Core File: The Abyssal Guardian Coelacanth has protected this trench for ten millennia. It will not yield.",
        commLine: { s: "D", l: "Guardian signature confirmed on radar. Time to earn our passage." }
      },
    },
    2: {
      1: {
        name: "2.1 Sector",
        shortName: "2.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Calcified Spore Clouds",
        classifiedLog: "Haven-7 Archive: The Great Dying bleached this colony in a single hour. Nothing living was spared.",
        commLine: { s: "D", l: "Bleached coral as far as the eye can see. Pure silence." }
      },
      2: {
        name: "2.2 Sector",
        shortName: "2.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Fossilized Bone Hazard",
        classifiedLog: "Xenobiology: The ribcage belongs to an organism larger than any dreadnought in the Terran fleet.",
        commLine: { s: "N", l: "Flying between ancient rib arches. Sensors picking up residual marrow radiation." }
      },
      3: {
        name: "2.3 Sector",
        shortName: "2.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Ghost Warship Phantoms",
        classifiedLog: "Navy Casualty Record: 3rd Heavy Flotilla lost during the first contact skirmish. Their automated guns still fire.",
        commLine: { s: "C", l: "I recognize those hull numbers. Old Navy brothers trapped in the reef." }
      },
      4: {
        name: "2.4 Sector",
        shortName: "2.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Neurotoxin Polyp Thickets",
        classifiedLog: "Haven-7 Bio-Hazmat: Neurotoxins attack synaptic neural links, causing control lag in pilot rigs.",
        commLine: { s: "L", l: "The purple flowers... they're trying to put my mind to sleep, Daddy." }
      },
      5: {
        name: "2.5 Sector",
        shortName: "2.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Crystalline Resonance Shards",
        classifiedLog: "Dr. Marcus Star Log #12: When the crystals vibrate, they project auditory memories of people you love.",
        commLine: { s: "D", l: "I hear music from home. Stay sharp, it's just crystal resonance." }
      },
      6: {
        name: "2.6 Sector",
        shortName: "2.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Amphitheater Sound Cannons",
        classifiedLog: "Precursor Cipher: This arena tested warrior ships in ritual combat before the Fall.",
        commLine: { s: "T", l: "Stone amphitheater ahead. Prepare for an ambush in the center ring." }
      },
      7: {
        name: "2.7 Sector",
        shortName: "2.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Prismatic Light Flares",
        classifiedLog: "Sensor Report: Light bouncing through these diamond pillars can blind target acquisition sensors.",
        commLine: { s: "N", l: "Prismatic glare is splitting our HUD crosshairs. Fire on physical telemetry." }
      },
      8: {
        name: "2.8 Sector",
        shortName: "2.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Ossuary Silt Traps",
        classifiedLog: "Salvage Memo: Billions of bio-synthetic components buried in the silt bed. High scrap concentration.",
        commLine: { s: "D", l: "Scrap signals lighting up the board. Harvest what we can on the fly." }
      },
      9: {
        name: "2.9 Sector",
        shortName: "2.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Memory Vault Defense Grid",
        classifiedLog: "Haven-7 Tactical: The inner sanctum is shielded by a holographic matrix powered by Precursor souls.",
        commLine: { s: "L", l: "The vault doors are opening, Daddy... they're crying out for release." }
      },
      10: {
        name: "2.10 Sector",
        shortName: "2.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Vault Golem Prismatic Beam",
        classifiedLog: "Final Precursor Log: The Vault Golem was built from our collective grief. Strike its heart to set it free.",
        commLine: { s: "D", l: "Vault Golem is assembling! Break its crystal armor before it fires!" }
      },
    },
    3: {
      1: {
        name: "3.1 Sector",
        shortName: "3.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Sub-Zero Nitrogen Brine",
        classifiedLog: "Europa Exploration File: Water temperature under the ice sheet sits at -4°C with heavy salt saturation.",
        commLine: { s: "D", l: "Europa's sub-glacial ocean. The cradle of the Coelacanths." }
      },
      2: {
        name: "3.2 Sector",
        shortName: "3.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Cryogenic Geyser Eruptions",
        classifiedLog: "Haven-7 Geological: Geysers erupt every 8 seconds, launching ice shrapnel at supersonic speeds.",
        commLine: { s: "T", l: "Geysers blowing from the ice floor! Keep your elevation high!" }
      },
      3: {
        name: "3.3 Sector",
        shortName: "3.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Bio-Fabricator Prototype Swarms",
        classifiedLog: "Ophion Design Note: The prototype embryos lack cognitive dampers. They attack anything that generates heat.",
        commLine: { s: "N", l: "Unfinished Coelacanth prototypes detected. They're drawn to our engines." }
      },
      4: {
        name: "3.4 Sector",
        shortName: "3.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Thermal Vent Shockwaves",
        classifiedLog: "Thermal Scan: Deep geothermal fractures provide the only warmth in this frozen grave.",
        commLine: { s: "D", l: "Ride the warm updrafts from the fissure. It'll restore engine efficiency." }
      },
      5: {
        name: "3.5 Sector",
        shortName: "3.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Incubator Pylon Shockfields",
        classifiedLog: "Automated Defense Log: High-voltage cables connect the hatchery pylons. Sever them to advance.",
        commLine: { s: "L", l: "The incubator eggs are pulsing in rhythm with my heartbeat..." }
      },
      6: {
        name: "3.6 Sector",
        shortName: "3.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Fractured Ice Shelf Collapses",
        classifiedLog: "Structural Warning: Overhead ice shelves are cracking under sonic vibrations from our weapons.",
        commLine: { s: "T", l: "Ice ceiling is coming down! Throttle up and clear the corridor!" }
      },
      7: {
        name: "3.7 Sector",
        shortName: "3.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Prototype Discard Trenches",
        classifiedLog: "Ophion Personal Log: Thousands of failed models were dumped here. I was the only one that achieved balance.",
        commLine: { s: "N", l: "This was Ophion's graveyard before he found Haven-7. A heavy price was paid." }
      },
      8: {
        name: "3.8 Sector",
        shortName: "3.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Cryo-Stasis Chamber Sentry Grid",
        classifiedLog: "Terran Intelligence: Navy tried to weaponize these stasis pods. The automated defenses turned on them.",
        commLine: { s: "C", l: "Navy survey team was wiped here in '62. The sentry turrets are still hot." }
      },
      9: {
        name: "3.9 Sector",
        shortName: "3.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Nursery Sanctum Gates",
        classifiedLog: "Precursor Nursery Codex: Only those carrying the spark of ancient kinship may enter the Queen's chamber.",
        commLine: { s: "L", l: "The Queen knows we're outside, Daddy. She's humming a lullaby." }
      },
      10: {
        name: "3.10 Sector",
        shortName: "3.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Hatchery Queen Cryo-Burst",
        classifiedLog: "Haven-7 Bio-Registry: The Hatchery Queen generates absolute zero fields that instantly shatter steel.",
        commLine: { s: "D", l: "Queen Coelacanth has surfaced! Focus all heat ordnance on her core!" }
      },
    },
    4: {
      1: {
        name: "4.1 Sector",
        shortName: "4.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Tachyon Plasma Refraction",
        classifiedLog: "Nebula Science Report: The Veil Nebula bends local spacetime, creating non-Euclidean flight corridors.",
        commLine: { s: "D", l: "The Veil Nebula. The stars look like they're melting into water." }
      },
      2: {
        name: "4.2 Sector",
        shortName: "4.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Quantum Mirages",
        classifiedLog: "Pilot Advisory: Target blips on radar may represent past or future positions of hostile craft.",
        commLine: { s: "N", l: "Sensors showing three targets for every drone. Shoot the one with engine wake." }
      },
      3: {
        name: "4.3 Sector",
        shortName: "4.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Supernova Dust Clouds",
        classifiedLog: "Astrophysics File: Heavy metal dust clouds strip shields if flown through at maximum velocity.",
        commLine: { s: "T", l: "Stardust is scraping the paint clean off my armor. Watch your speed." }
      },
      4: {
        name: "4.4 Sector",
        shortName: "4.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Thought-Form Anomalies",
        classifiedLog: "Dr. Marcus Star Log #25: In the Veil, the ship's computers started generating poetry instead of math.",
        commLine: { s: "L", l: "The nebula wants to tell us a story, Daddy. It's about a world made of glass." }
      },
      5: {
        name: "4.5 Sector",
        shortName: "4.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Plasma Storm Fronts",
        classifiedLog: "Thermal Warning: Ionized gas cyclones reach speeds exceeding Mach 12.",
        commLine: { s: "D", l: "Plasma squall ahead! Dive into the magnetic channel to stay stable." }
      },
      6: {
        name: "4.6 Sector",
        shortName: "4.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Stellar Nursery Flares",
        classifiedLog: "Haven-7 Astrometry: Baby stars igniting inside the dust pillars create spontaneous radiation surges.",
        commLine: { s: "N", l: "Protostar flare warning! Shield deflectors to 100%." }
      },
      7: {
        name: "4.7 Sector",
        shortName: "4.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Temporal Lag Corridors",
        classifiedLog: "Quantum Field Note: Radio transmissions here arrive 10 seconds before they are transmitted.",
        commLine: { s: "T", l: "I'm hearing my own callout on the radio before I say it. Disorienting." }
      },
      8: {
        name: "4.8 Sector",
        shortName: "4.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Ghost Ship Phantoms",
        classifiedLog: "Navy Search & Rescue: 12 destroyers vanished into the Veil in 2074. Their quantum silhouettes remain.",
        commLine: { s: "C", l: "My old flight academy training cruiser is drifting in that cloud. Eerie." }
      },
      9: {
        name: "4.9 Sector",
        shortName: "4.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Dreamer Conduit Threshold",
        classifiedLog: "Haven-7 Telemetry: The Dreamer's consciousness converges into a singular point of light.",
        commLine: { s: "L", l: "We're almost at the heart of the dream. Don't let go of what is real, Daddy." }
      },
      10: {
        name: "4.10 Sector",
        shortName: "4.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Dreamer Golem Reality Warp",
        classifiedLog: "Classified Precursor Record: The Dreamer cannot be killed, only awakened. Shatter its cosmic anchors.",
        commLine: { s: "D", l: "The Dreamer Golem is manifesting! Fire across its anchor points!" }
      },
    },
    5: {
      1: {
        name: "5.1 Sector",
        shortName: "5.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Ice-Ring Shrapnel Field",
        classifiedLog: "Ring Navigation Guide: Saturn's B-ring consists of pure water ice chunks traveling at 15 km/s.",
        commLine: { s: "D", l: "Saturn's rings. Trillions of tons of frozen shrapnel spinning at orbital speed." }
      },
      2: {
        name: "5.2 Sector",
        shortName: "5.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Umbra Stealth Cloaking",
        classifiedLog: "Navy Tactical Directive: Umbra Squad interceptors use active radar absorbing carbon metamaterials.",
        commLine: { s: "C", l: "My former squadron is lurking in the ice shadows. Watch your six." }
      },
      3: {
        name: "5.3 Sector",
        shortName: "5.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Railgun Perimeter Batteries",
        classifiedLog: "Navy Recon: Automated defense satellites stationed every 50 kilometers along the ring plane.",
        commLine: { s: "T", l: "Heavy railgun batteries mounted on the icebergs. Knock out their power generators." }
      },
      4: {
        name: "5.4 Sector",
        shortName: "5.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Cryo-Nitrogen Geysers",
        classifiedLog: "Haven-7 Geology: Sub-surface geysers on ice boulders venting liquid nitrogen plumes.",
        commLine: { s: "N", l: "Nitrogen geysers venting across our flight path. Bank left to clear the vapor." }
      },
      5: {
        name: "5.5 Sector",
        shortName: "5.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Diamond Dust Clouds",
        classifiedLog: "Sensor Advisory: Microscopic diamond crystals interfere with laser weapons, reducing beam coherence.",
        commLine: { s: "D", l: "Lasers diffusing in the diamond dust! Switch to kinetic rockets!" }
      },
      6: {
        name: "5.6 Sector",
        shortName: "5.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Destroyer Graveyard Alley",
        classifiedLog: "Salvage Registry: Wreckage from the Second Interplanetary War trapped in orbital resonance.",
        commLine: { s: "D", l: "Dozens of Navy destroyers smashed together like frozen scrap cars." }
      },
      7: {
        name: "5.7 Sector",
        shortName: "5.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Navy Electronic Warfare Jamming",
        classifiedLog: "Comms Log: Navy command broadcasting broadband white noise across all standard frequencies.",
        commLine: { s: "T", l: "Comms are jammed with military noise! Switch to Haven-7 direct laser link!" }
      },
      8: {
        name: "5.8 Sector",
        shortName: "5.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Absolute Zero Pockets",
        classifiedLog: "Cryo Physics: Shadowed side of ring boulders reaches 2.7 Kelvin, causing superconductive hull stress.",
        commLine: { s: "N", l: "Entering the dark side of the ring. Hull heaters on standby." }
      },
      9: {
        name: "5.9 Sector",
        shortName: "5.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Fortress Kraken Approach",
        classifiedLog: "Navy Combat Log: The Kraken Mobile Fortress is the flagship of EDC ring suppression forces.",
        commLine: { s: "C", l: "Kraken Fortress sighted. This was Crane's master weapon. Time to tear it apart." }
      },
      10: {
        name: "5.10 Sector",
        shortName: "5.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Kraken Dreadnought Battery",
        classifiedLog: "Navy Black-Ops File: Destroying the Kraken will break EDC's blockade of the outer solar system.",
        commLine: { s: "D", l: "Kraken is opening all torpedo tubes! Evade the volley and hit the bridge!" }
      },
    },
    6: {
      1: {
        name: "6.1 Sector",
        shortName: "6.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Supernova Slag Fallout",
        classifiedLog: "Haven-7 Sensor Sweep: Surface temperatures on asteroid fragments exceed 1200°C.",
        commLine: { s: "D", l: "Fire nebula. Everything out here has been cooked to molten slag." }
      },
      2: {
        name: "6.2 Sector",
        shortName: "6.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Magma Eruption Columns",
        classifiedLog: "Volcanic Advisory: Subterranean lava reservoirs bursting into the vacuum of space.",
        commLine: { s: "N", l: "Magma plumes arcing across the sector like burning bridges. Fly under the arc." }
      },
      3: {
        name: "6.3 Sector",
        shortName: "6.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Foundry Drone Patrols",
        classifiedLog: "Forge-Mind Automation: Automated smelting drones convert space wreckage into combat hulls.",
        commLine: { s: "T", l: "Smelter drones are harvesting the asteroid belt. Break up their convoy." }
      },
      4: {
        name: "6.4 Sector",
        shortName: "6.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Solar Flare Radiation Waves",
        classifiedLog: "Stellar Warning: Coronal mass ejections from the dying star sweep the sector every 20 seconds.",
        commLine: { s: "D", l: "Solar flare incoming! Tuck behind that iron asteroid for cover!" }
      },
      5: {
        name: "6.5 Sector",
        shortName: "6.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Obsidian Chasm Vents",
        classifiedLog: "Haven-7 Survey: Razor-sharp volcanic glass formations lining the interior canyons.",
        commLine: { s: "L", l: "The glass is glowing red in the dark... it looks like burning veins." }
      },
      6: {
        name: "6.6 Sector",
        shortName: "6.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Crucible Smelting Chambers",
        classifiedLog: "Forge Architecture: Giant magnetic containment vats holding thousands of tons of liquid titanium.",
        commLine: { s: "N", l: "Crucible vats ahead. If they rupture, the whole corridor will be flooded with slag." }
      },
      7: {
        name: "6.7 Sector",
        shortName: "6.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Plasma Stream Overheats",
        classifiedLog: "Thermal Danger: Laser weapon heat buildup is tripled in this atmospheric density.",
        commLine: { s: "T", l: "Pace your shots, Darius! The ambient heat is redlining our weapon radiators." }
      },
      8: {
        name: "6.8 Sector",
        shortName: "6.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Molten Core Conduit",
        classifiedLog: "Haven-7 Tactical: The power conduit feeding the master forge is exposed along the basalt trench.",
        commLine: { s: "D", l: "I see the power conduits. Blow the cooling lines to force an emergency shutdown." }
      },
      9: {
        name: "6.9 Sector",
        shortName: "6.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Master Forge Gate",
        classifiedLog: "Precursor Foundry Log: The Forge-Mind has operated without human supervision for five centuries.",
        commLine: { s: "C", l: "The main foundry gates are opening. Automated guardians are rolling out." }
      },
      10: {
        name: "6.10 Sector",
        shortName: "6.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Forge-Mind Leviathan Crucible",
        classifiedLog: "Classified Core Directive: Destroy the central smelting core to permanently disable automated drone production.",
        commLine: { s: "D", l: "Forge-Mind is engaging! Strike the crucible coolers and shatter its frame!" }
      },
    },
    7: {
      1: {
        name: "7.1 Sector",
        shortName: "7.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Jovian Hurricane Winds",
        classifiedLog: "Atmospheric Flight Memo: Winds in the Storm Belt reach 5,000 km/h with vertical wind shear.",
        commLine: { s: "D", l: "Jupiter's Storm Belt. Five thousand mile-an-hour gale winds slamming into the hull." }
      },
      2: {
        name: "7.2 Sector",
        shortName: "7.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Conductive Lightning Grids",
        classifiedLog: "Haven-7 Physics: Atmospheric static builds until it discharges across conductive metallic surfaces.",
        commLine: { s: "N", l: "Static building on the cockpit canopy. Disperse shields before the lightning strikes!" }
      },
      3: {
        name: "7.3 Sector",
        shortName: "7.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Storm-Hawk Dive Attacks",
        classifiedLog: "Xeno-Aviation: Bio-synthetic predatory birds that hunt by riding atmospheric shockwaves.",
        commLine: { s: "T", l: "Predator drones diving out of the storm clouds! Flak burst on my mark!" }
      },
      4: {
        name: "7.4 Sector",
        shortName: "7.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Static Cloud Pillars",
        classifiedLog: "Radar Telemetry: Dense ion clouds obscure all optical and infrared sensor equipment.",
        commLine: { s: "L", l: "The lightning is so bright... but behind it, I can hear a voice singing." }
      },
      5: {
        name: "7.5 Sector",
        shortName: "7.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Thunderhead Downdrafts",
        classifiedLog: "Flight Safety Log: Downdrafts can crush an unshielded fighter against denser Jovian atmospheric layers.",
        commLine: { s: "D", l: "Downdraft pulling us down! Boost engines to escape the atmospheric sink!" }
      },
      6: {
        name: "7.6 Sector",
        shortName: "7.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Atmospheric Pressure Choke",
        classifiedLog: "Structural Telemetry: Pressure at this depth is 50 times Terran sea level.",
        commLine: { s: "N", l: "Hull groaning under atmospheric pressure. We need to reach the eye of the storm." }
      },
      7: {
        name: "7.7 Sector",
        shortName: "7.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Ball Lightning Clusters",
        classifiedLog: "Physics Report: Stable plasma spheres that seek out active electrical power sources.",
        commLine: { s: "T", l: "Ball lightning drifting toward our engines! Cut power for two seconds to break lock!" }
      },
      8: {
        name: "7.8 Sector",
        shortName: "7.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Eye Wall Perimeter Gale",
        classifiedLog: "Meteorology Report: The boundary of the storm eye generates continuous cyclonic tornadoes.",
        commLine: { s: "D", l: "Punching through the eye wall! Hold the flight stick with both hands!" }
      },
      9: {
        name: "7.9 Sector",
        shortName: "7.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Storm-Singer Sanctuary",
        classifiedLog: "Haven-7 Acoustic Log: The Storm-Singer chose this tempest to hide its grief from the galaxy.",
        commLine: { s: "L", l: "We made it to the quiet center. The Storm-Singer is right in front of us." }
      },
      10: {
        name: "7.10 Sector",
        shortName: "7.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Storm-Singer Colossus Eye",
        classifiedLog: "Classified Sanctuary Log: Free the Storm-Singer from its eternal storm loop.",
        commLine: { s: "D", l: "Storm-Singer is charging its lightning vortex! Evade the funnel and attack the core!" }
      },
    },
    8: {
      1: {
        name: "8.1 Sector",
        shortName: "8.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Derelict Minefield Clusters",
        classifiedLog: "Navy Salvage Registry: 400 Navy warships abandoned during the Precursor Offensive of 2070.",
        commLine: { s: "D", l: "The ghost fleet. Hundreds of battleships floating dead in the black." }
      },
      2: {
        name: "8.2 Sector",
        shortName: "8.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Automated Defense Turrets",
        classifiedLog: "Navy Defense Network: Drone turrets programmed to shoot any craft not broadcasting EDC encrypted codes.",
        commLine: { s: "C", l: "Those point-defense turrets are still hunting on Admiral Crane's orders." }
      },
      3: {
        name: "8.3 Sector",
        shortName: "8.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Boarding Pod Ambushers",
        classifiedLog: "Tactical Warning: Automated boarding pods hidden in the hollow hangar bays of dead carriers.",
        commLine: { s: "T", l: "Boarding pods launching from the carrier wrecks! Shoot them down before they attach!" }
      },
      4: {
        name: "8.4 Sector",
        shortName: "8.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Nuclear Reactor Radiation Leaks",
        classifiedLog: "Radiation Warning: Breached fission reactors leaking radioactive coolant into the debris field.",
        commLine: { s: "N", l: "Radiation spiking in sector four. Keep distance from the cracked reactor cores." }
      },
      5: {
        name: "8.5 Sector",
        shortName: "8.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Hull Fragment Corridors",
        classifiedLog: "Salvage Guide: Razor-sharp armor plates drifting across narrow flight channels.",
        commLine: { s: "D", l: "Weaving through shattered battlecruiser hulls. Watch the protruding superstructure." }
      },
      6: {
        name: "8.6 Sector",
        shortName: "8.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Automated Dreadnought Patrols",
        classifiedLog: "Navy Combat Log: Autonomous patrol cruisers maintaining defensive patrols around the flagship.",
        commLine: { s: "C", l: "Heavy automated dreadnought on patrol. It hasn't received a stand-down order in 30 years." }
      },
      7: {
        name: "8.7 Sector",
        shortName: "8.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Sensor Decoy Drones",
        classifiedLog: "Tactical Intercept: Fleet decoys projecting false capital ship radar signatures.",
        commLine: { s: "T", l: "Don't trust the radar blips. Verify targets through the optical scope." }
      },
      8: {
        name: "8.8 Sector",
        shortName: "8.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Flagship Escort Ring",
        classifiedLog: "Haven-7 Intelligence: The Goliath's escort ring is armed with synchronized particle lances.",
        commLine: { s: "N", l: "Synchronized particle lance batteries sighted. We need to disable the relay ships." }
      },
      9: {
        name: "8.9 Sector",
        shortName: "8.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Goliath Supercarrier Sanctum",
        classifiedLog: "Admiral Crane Archive: The Goliath was designed to be the ultimate Terran command nexus.",
        commLine: { s: "D", l: "Flagship Goliath dead ahead. Crane's automated ghost is waiting on the bridge." }
      },
      10: {
        name: "8.10 Sector",
        shortName: "8.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Admiral Crane AI Flagship",
        classifiedLog: "Classified EDC Archive: Purge Admiral Crane's digital ghost to liberate the fleet archives.",
        commLine: { s: "D", l: "Goliath main batteries powering up! Break its shield generator arrays!" }
      },
    },
    9: {
      1: {
        name: "9.1 Sector",
        shortName: "9.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Synaptic Hive Spores",
        classifiedLog: "Haven-7 Biology: Spores create a direct neural link between the Hive Mother and all living organisms.",
        commLine: { s: "D", l: "The Xenomorph Hive. The planet itself is breathing and watching us." }
      },
      2: {
        name: "9.2 Sector",
        shortName: "9.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Bio-Plasma Spitter Nests",
        classifiedLog: "Xenobiology: Bio-plasma spitters fire corrosive acid globs that dissolve energy shields.",
        commLine: { s: "N", l: "Acid spitters firing from the bio-towers! Dodge laterally to avoid the splash!" }
      },
      3: {
        name: "9.3 Sector",
        shortName: "9.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Organic Chitin Walls",
        classifiedLog: "Haven-7 Tactical: Chitin walls regenerate rapidly unless destroyed with sustained high-explosive ordnance.",
        commLine: { s: "T", l: "Chitin walls are closing the tunnel! Blast a hole through the membrane!" }
      },
      4: {
        name: "9.4 Sector",
        shortName: "9.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Synaptic Hallucinations",
        classifiedLog: "Psychic Telemetry: The Hive projects memories of loved ones to lure pilots into organic pods.",
        commLine: { s: "L", l: "Daddy... the walls are whispering in Mom's voice. Don't listen to them!" }
      },
      5: {
        name: "9.5 Sector",
        shortName: "9.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Egg Nursery Hatcheries",
        classifiedLog: "Xeno-Reproduction: Thousands of bio-construct eggs pulsing with electric bioluminescence.",
        commLine: { s: "N", l: "Nursery sector. Wipe out the egg clusters before they hatch into interceptors." }
      },
      6: {
        name: "9.6 Sector",
        shortName: "9.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Acidic Fluid Waterfalls",
        classifiedLog: "Chemical Warning: Bio-acid waterfalls flowing from the ceiling into digestive pools below.",
        commLine: { s: "D", l: "Bio-acid dripping from the ceiling. Keep flight trim tight and centered." }
      },
      7: {
        name: "9.7 Sector",
        shortName: "9.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Neural Bridge Nodes",
        classifiedLog: "Haven-7 Science: Synaptic nodes transferring stolen memories to the central hive mind.",
        commLine: { s: "T", l: "Destroy the neural bridge nodes. It'll blind their defensive coordination." }
      },
      8: {
        name: "9.8 Sector",
        shortName: "9.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Chitin Brute Vanguard",
        classifiedLog: "Combat Threat: Armored bio-titans designed to absorb fleet-level missile bombardments.",
        commLine: { s: "N", l: "Chitin Brute charging down the corridor! Aim for the soft joints under its carapace!" }
      },
      9: {
        name: "9.9 Sector",
        shortName: "9.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Hive Mother Throne Chamber",
        classifiedLog: "Haven-7 Intel: The Hive Mother sits atop a mountain of calcified Precursor technology.",
        commLine: { s: "L", l: "She's waiting for us in the center of the web. Her thoughts are overwhelming." }
      },
      10: {
        name: "9.10 Sector",
        shortName: "9.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Hive Mother Bio-Nexus",
        classifiedLog: "Classified Core File: Destroying the Hive Mother will sever the synaptic web and free all trapped minds.",
        commLine: { s: "D", l: "Hive Mother has uncoiled! Sever her neural tentacles and break her crown!" }
      },
    },
    10: {
      1: {
        name: "10.1 Sector",
        shortName: "10.1 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Event Horizon Gravitational Shear",
        classifiedLog: "Core Physics: Gravitational force near the singularity bends time by a factor of 100.",
        commLine: { s: "D", l: "The Core Rift. The edge of reality itself. We made it, Lyra." }
      },
      2: {
        name: "10.2 Sector",
        shortName: "10.2 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Chrono-Rift Temporal Fractures",
        classifiedLog: "Haven-7 Astrometry: Space and time are shattering into discrete, repeating code fragments.",
        commLine: { s: "N", l: "Enemies are rewinding their attack vectors! Anticipate the temporal loop!" }
      },
      3: {
        name: "10.3 Sector",
        shortName: "10.3 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Singularity Code Streams",
        classifiedLog: "Precursor Matrix: The universe's source code is leaking into observable space as glowing green runes.",
        commLine: { s: "L", l: "I can read the code in the dark, Daddy. It says... everything is connected." }
      },
      4: {
        name: "10.4 Sector",
        shortName: "10.4 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Null-Space Blackouts",
        classifiedLog: "Quantum Physics: Pockets of absolute non-existence that erase weapons and shields on contact.",
        commLine: { s: "T", l: "Null-space rifts opening ahead! Steer clear of the black voids!" }
      },
      5: {
        name: "10.5 Sector",
        shortName: "10.5 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Paradox Drone Phantoms",
        classifiedLog: "Temporal Mechanics: Drones existing in multiple timelines simultaneously.",
        commLine: { s: "N", l: "Paradox fighters are phased across timelines. Hit them when they fully materialize." }
      },
      6: {
        name: "10.6 Sector",
        shortName: "10.6 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Tachyon Mirror Shards",
        classifiedLog: "Haven-7 Core: Reflections in the rift show alternate endings of our journey.",
        commLine: { s: "D", l: "I see ships from every timeline flying alongside us. We're not alone." }
      },
      7: {
        name: "10.7 Sector",
        shortName: "10.7 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Singularity Horizon Chasm",
        classifiedLog: "Astrophysics Warning: Escape velocity here requires 100% quantum overdrive.",
        commLine: { s: "T", l: "Engines at 110%! Keep forward velocity or get pulled into the core!" }
      },
      8: {
        name: "10.8 Sector",
        shortName: "10.8 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Precursor Throne Spires",
        classifiedLog: "Architectural File: The ancient monument where the first Cyber Coelacanth was conceived.",
        commLine: { s: "L", l: "The spires are singing the first song of creation. We're almost at the throne." }
      },
      9: {
        name: "10.9 Sector",
        shortName: "10.9 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "Architect Prime Threshold",
        classifiedLog: "Omega Directive: The Architect awaits to administer the final cosmological test.",
        commLine: { s: "A", l: "You who travel through time and sorrow... approach the final threshold..." }
      },
      10: {
        name: "10.10 Sector",
        shortName: "10.10 Sector",
        landmark: "coral_spire",
        particlePreset: "marine_snow",
        accentColor: "#00ffff",
        skyGradient: ["#020b1e", "#041536", "#06224e"],
        intel: "Navigating active sector airspace.",
        hazard: "The Cyber Coelacanth Singularity",
        classifiedLog: "Canonical Omega Record: The Cyber Coelacanth awakens in its transcendent divine form. Deliver humanity's answer.",
        commLine: { s: "D", l: "The Cyber Coelacanth has awakened! All weapons, all hearts, full burn!" }
      },
    },
  },
  // Helper method to retrieve sector intel and level metadata safely (GRO-4203)
  getLevelInfo(biome, level) {
    const b = Math.max(1, Math.min(10, biome || 1));
    const l = Math.max(1, Math.min(10, level || 1));
    if (this.levelDetails[b] && this.levelDetails[b][l]) {
      const data = this.levelDetails[b][l];
      return {
        sectorId: `b${b}_l${l}`,
        biome: b,
        level: l,
        ...data,
        hazard: data.hazard || `Hazard Level ${b}: Environmental Distortion`,
        classifiedLog: data.classifiedLog || `[CLASSIFIED ARCHIVE ${b}.${l}]: Precursor energy signature active in this sector. Proceed with caution.`,
        commLine: data.commLine || { s: 'D', l: `Entering sector ${b}.${l}. Weapons hot.` }
      };
    }
    return {
      sectorId: `b${b}_l${l}`,
      biome: b,
      level: l,
      name: `${b}.${l} Sector Passage`,
      shortName: 'Sector Passage',
      landmark: 'coral_spire',
      particlePreset: 'marine_snow',
      accentColor: '#00ffff',
      skyGradient: ['#020418', '#06102a', '#0a1a3a'],
      hazard: 'Standard Sector Hostility',
      intel: 'Navigating active sector airspace. Hostile fleet resistance detected.',
      classifiedLog: '[HAVEN-7 TELEMETRY]: Deep sector scans confirm high-density Precursor scrap reserves.',
      commLine: { s: 'D', l: `Sector ${b}.${l} in sight. Let's clear the path.` }
    };
  },

  getSectorIntel(biome, level) {
    return this.getLevelInfo(biome, level);
  }
};

// Expose on window for global access
if (typeof window !== 'undefined') {
  window.BIOME_DATA = BIOME_DATA;
}
if (typeof global !== 'undefined') {
  global.BIOME_DATA = BIOME_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = BIOME_DATA;
}
